version: '3.9'

services:
  nginx:
    image: macbre/nginx-http3:1.23.1
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../nginx/out/crypto/:/etc/markup2/
    networks:
      - api-gateaway
    ports:
      - 443:443/tcp
      - 443:443/udp
      - 80:80/tcp
      - 80:80/udp
    depends_on:
      - markupapi
    restart: always


  markupapi-dev:
    extends:
      file: ../backend/docker/common-services.yml
      service: markupapi
    image: cosmtrek/air
    working_dir: /tmp/project
    entrypoint: ["/go/bin/air", "-c", "markupapi/.air.toml"]
    networks:
      - api-gateaway
      - backend
    volumes:
      - ../backend:/tmp/project
      - ../backend/config.yaml:/usr/local/etc/markup2.yaml
    restart: always

networks:
  api-gateaway:
    driver: bridge

  backend:
    driver: bridge
    internal: true
