FROM node:18.15.0-alpine3.17 as build

WORKDIR /usr/frontend

COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install

COPY ./frontend ./
RUN npm run build

FROM macbre/nginx-http3:1.23.1

COPY --from=build /usr/frontend/build /usr/share/nginx/html
