version: '3.9'

services:
  markupapi:
    expose:
      - 10001
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://markaupapi:10001/readiness"]
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 10s
