name: Go Integration

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.go'
permissions:
  contents: read
jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: test
          POSTGRES_DB: markup2
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: test
          MONGO_INITDB_DATABASE: markup2
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: backend/go.mod

      - name: Build app
        run: make b-build

      - name: Start backend
        run: ${{ github.workspace }}/backend/out/markupapi.out --config ${{ github.workspace }}/backend/config.ci.yaml &

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/regress.json" -e "${{ github.workspace }}/backend/test/regress/CI.postman_environment.json" --integration-id "138491-${{ github.run_id }}" --working-dir "${{ github.workspace }}/backend/test/regress"
